fix: objectId casting now working
mia-platform/crud-service pull request #111
Opened 2023-06-23 08:02 UTC by giuliowaitforitdavide

## Pull Request Type

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] Other... Please describe:

## Description

The getList was returing an error `Cannot read properties of undefined, reading toString()` when try to cast ObjectIds

## PR Checklist

- [X] The commit message follows our guidelines included in the [CONTRIBUTING.md](../CONTRIBUTING.md#how-to-submit-a-pr)
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

2023-06-23 13:53 UTC, ThisIsDemetrio approved these changes
lgtm

2023-06-23 14:34 UTC, hiimjako requested changes
It seems fine, but if you try to look at the generated swagger you will see that it some fields it shows: `Unknown Type: string,object` or `Unknown Type: array,string`.
Can you try to give it a look? It seems an error related to JSONschemaGenerator and/or ajv configuration.

2023-06-23 14:39 UTC, danibix95 commented
> It seems fine, but if you try to look at the generated swagger you will see that it some fields it shows: `Unknown Type: string,object` or `Unknown Type: array,string`. Can you try to give it a look? It seems an error related to JSONschemaGenerator and/or ajv configuration.

@giuliowaitforitdavide

2023-06-27 10:45 UTC, giuliowaitforitdavide commented
> It seems fine, but if you try to look at the generated swagger you will see that it some fields it shows: `Unknown Type: string,object` or `Unknown Type: array,string`. Can you try to give it a look? It seems an error related to JSONschemaGenerator and/or ajv configuration.

Fixed

2023-06-28 08:45 UTC, giuliowaitforitdavide commented on lib/schemaGetters.js
> +        },
Fixed

2023-06-30 08:48 UTC, hiimjako commented
Still have the same problem on `ObjectId`, `Date` and `Array of object` field. The fix should be something similar to the previous ones.

2023-06-30 13:34 UTC, hiimjako approved these changes
LGTM, good job!

2023-06-30 16:12 UTC, merged